apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: gobble
  labels:
    app: ollama
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: uberchuckie/ollama-intel-gpu:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_HOST
              valueFrom:
                secretKeyRef:
                  name: gobble-secrets
                  key: ollama_host
            - name: ONEAPI_DEVICE_SELECTOR
              value: "level_zero:0"
            - name: OLLAMA_NUM_PARALLEL
              value: "1"
          volumeMounts:
            - mountPath: /root/.ollama
              name: models-volume
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
              gpu.intel.com/i915: "1"
            limits:
              cpu: "2"
              memory: "4Gi"
              gpu.intel.com/i915: "1"
          securityContext:
            privileged: true
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: gobble-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-lb
  namespace: gobble
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
      name: http
  type: LoadBalancer
