apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: gobble
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_HOST
              valueFrom:
                secretKeyRef:
                  name: gobble-secrets
                  key: ollama_host
          volumeMounts:
            - mountPath: /root/.ollama
              name: models-volume
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: gobble-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-lb
  namespace: gobble
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
      name: http
  type: LoadBalancer
