apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gobble-models-pvc
  namespace: gobble
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: microk8s-hostpath
